
package Vista;

/**
 *
 * @author manue
 */
public class VistaInicioSocios extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicioSocios
     */
    public VistaInicioSocios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        nuevoSocio = new javax.swing.JButton();
        bajaSocio = new javax.swing.JButton();
        actualizarSocio = new javax.swing.JButton();

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Socio", "Nombre", "DNI", "Fecha de Nacimiento", "Teléfono", "Correo", "Fecha de Alta", "Categoría"
            }
        ));
        jScrollPane2.setViewportView(jTableSocios);

        nuevoSocio.setText("Nuevo Socio");

        bajaSocio.setText("Baja de Socio");
        bajaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaSocioActionPerformed(evt);
            }
        });

        actualizarSocio.setText("Actualización de Socio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nuevoSocio)
                .addGap(100, 100, 100)
                .addComponent(bajaSocio)
                .addGap(98, 98, 98)
                .addComponent(actualizarSocio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoSocio)
                    .addComponent(bajaSocio)
                    .addComponent(actualizarSocio)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bajaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaSocioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizarSocio;
    public javax.swing.JButton bajaSocio;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableSocios;
    public javax.swing.JButton nuevoSocio;
    // End of variables declaration//GEN-END:variables
}
