/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author manue
 */
public class VistaInicioMonitores extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicioMonitores
     */
    public VistaInicioMonitores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMonitores = new javax.swing.JTable();
        nuevoMonitor = new javax.swing.JButton();
        bajaMonitor = new javax.swing.JButton();
        actualizaciónMonitor = new javax.swing.JButton();

        jTableMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "DNI", "Teléfono", "Correo", "Fecha Incorporación", "Nick"
            }
        ));
        jScrollPane2.setViewportView(jTableMonitores);

        nuevoMonitor.setText("Nuevo Monitor");
        nuevoMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMonitorActionPerformed(evt);
            }
        });

        bajaMonitor.setText("Baja de Monitor");

        actualizaciónMonitor.setText("Actualización de Monitor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevoMonitor)
                .addGap(28, 28, 28)
                .addComponent(bajaMonitor)
                .addGap(35, 35, 35)
                .addComponent(actualizaciónMonitor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoMonitor)
                    .addComponent(bajaMonitor)
                    .addComponent(actualizaciónMonitor)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoMonitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizaciónMonitor;
    public javax.swing.JButton bajaMonitor;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableMonitores;
    public javax.swing.JButton nuevoMonitor;
    // End of variables declaration//GEN-END:variables
}
