/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author manue
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
    private java.awt.CardLayout cardLayout;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.cardLayout=new java.awt.CardLayout();
        panelContenedor.setLayout(this.cardLayout);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuItemInicio = new javax.swing.JMenuItem();
        menuMonitores = new javax.swing.JMenu();
        menuItemGestionMonitores = new javax.swing.JMenuItem();
        menuSocios = new javax.swing.JMenu();
        menuItemGestionSocios = new javax.swing.JMenuItem();
        menuActividades = new javax.swing.JMenu();
        menuItemGestionActividades = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión del Gimnasio \"Body Perfect\"");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menuInicio.setText("Inicio");

        menuItemInicio.setText("Inicio");
        menuInicio.add(menuItemInicio);

        menuBar.add(menuInicio);

        menuMonitores.setText("Monitores");

        menuItemGestionMonitores.setText("Gestión de Monitores");
        menuItemGestionMonitores.setActionCommand("GestionMonitores");
        menuItemGestionMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionMonitoresActionPerformed(evt);
            }
        });
        menuMonitores.add(menuItemGestionMonitores);

        menuBar.add(menuMonitores);

        menuSocios.setText("Socios");

        menuItemGestionSocios.setText("Gestión de Socios");
        menuItemGestionSocios.setActionCommand("GestionSocios");
        menuSocios.add(menuItemGestionSocios);

        menuBar.add(menuSocios);

        menuActividades.setText("Actividades");

        menuItemGestionActividades.setText("Gestión de Actividades");
        menuItemGestionActividades.setActionCommand("GestionActividades");
        menuActividades.add(menuItemGestionActividades);

        menuBar.add(menuActividades);

        menuSalir.setText("Salir");

        menuItemSalir.setText("Salir");
        menuItemSalir.setActionCommand("Salir");
        menuSalir.add(menuItemSalir);

        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemGestionMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionMonitoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemGestionMonitoresActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu menuActividades;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuInicio;
    public javax.swing.JMenuItem menuItemGestionActividades;
    public javax.swing.JMenuItem menuItemGestionMonitores;
    public javax.swing.JMenuItem menuItemGestionSocios;
    public javax.swing.JMenuItem menuItemInicio;
    public javax.swing.JMenuItem menuItemSalir;
    public javax.swing.JMenu menuMonitores;
    private javax.swing.JMenu menuSalir;
    public javax.swing.JMenu menuSocios;
    public javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables

    public void agregarPanel(javax.swing.JPanel panel, String nombre) {
        panelContenedor.add(panel, nombre);
    }
    
    public void mostrarPanel(String nombre) {
        cardLayout.show(panelContenedor, nombre);
    }
}
